packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 10080
trustPolicy: no-downgrade
blockExoticSubdeps: true
shamefullyHoist: true

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - less
  - nx
  - prisma
  - sharp
