packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 10080
trustPolicy: no-downgrade
blockExoticSubdeps: true
shamefullyHoist: true

auditConfig:
  ignoreGhsas:
    - GHSA-6g55-p6wh-862q
    - GHSA-r28c-9q8g-f849
    - GHSA-ggr8-5vv4-36mx
    - GHSA-3f6p-5ww8-9rcr

onlyBuiltDependencies:
  - '@clerk/shared'
  - '@parcel/watcher'
  - '@prisma/engines'
  - esbuild
  - less
  - nx
  - prisma
  - sharp
